services:
  - type: web
    name: fake-news-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fake-news-postgres
          property: connectionString

databases:
  - name: fake-news-postgres
    plan: free
